version: '3.9'
services:
  coral_inference:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: coral_inference
    privileged: true          # 필수: USB 장치 접근 허용 (권장 설정)
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - "/mnt/usb:/workspace"
      - "../../raspberry_coral_inference:/app/code"
    command: tail -f /dev/null
    restart: unless-stopped
