version: "3.9"
services:
  coral_inference:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: coral_inference
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command: tail -f /dev/null  # 컨테이너가 종료되지 않도록 유지
    restart: unless-stopped
