version: '3.9'
services:
  coral_inference:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: coral_inference
    privileged: true          # 필수: USB 및 카메라 장치 접근 허용
    devices:
      - /dev/vchiq:/dev/vchiq  # 라즈베리파이 카메라 장치 마운트
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - "/mnt/usb:/workspace"
      - "../../raspberry_coral_inference:/app/code"
    group_add:
      - video                # 컨테이너에 video 그룹 추가
    command: tail -f /dev/null
    restart: unless-stopped
